name: Iorgen lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with: {python-version: '3.10'}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pyyaml \
            'mypy==0.910' types-PyYAML 'pylint==2.11.1' 'black==21.8b0'
      - name: Run lint checks
        run: ./check_code.sh
