name: Iorgen lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: {python-version: 3.8}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pyyaml 'mypy==0.790' 'pylint==2.6.0' 'yapf==0.30.0'
      - name: Run lint checks
        run: ./check_code.sh
